### ISSUE TITLE
Allow configuring a volume sources by a secret

### ISSUE THREAD

**Issue by frank-bee** [metal3d/katenary#20]
Allow configuring a volume sourced by a secret similar how it's done with "katenary.io/configmap-volumes" --> but without providing the actual secret file (or maybe optionally)

**Comment by metal3d** [comment]
Hello,
Do you mean "docker secret" ? I never used it at this time but it should be possible.

**Comment by metal3d** [comment]
As the issue is very old, closing.

Please reopen if your request apply to the next v3 release.
