### ISSUE TITLE
Does this work on macos?

### ISSUE THREAD

**Issue by skiwheelr** [metal3d/katenary#63]
Can I use this with mac and if so, can it be added to homebrew?

**Comment by metal3d** [comment]
Hello,
There is a dawrin build, so you can theorically use it on Mac. At this time, I cannot be sure that it works correctly on Mac.
There is no Homebrew build for now, I will try as soon as I finalize the next iteration (dependency declaration, some fixes, better generation, everythin is in another branch)

I keep this opened to create the "brew" package in mind.

**Comment by VictoriaMOtus** [comment]
I was able to make this work, download the release for your arch (I am on an M1 macbook pro), move into your /usr/local/bin/dir, then `chmod +x ` the file.

**Comment by metal3d** [comment]
The next version will be tested on a Mac. It is a big refactor + more tests.

**Comment by metal3d** [comment]
Without any news, closing this issue.

The next release should work on Mac.
