### ISSUE TITLE
Bug: Underscores in docker-compose services names

### ISSUE THREAD

**Issue by unicode-it** [metal3d/katenary#74]
### Version

3, develop branch

### Reproduce

Create a docker-compose file with service names containing underscores and convert it. Same problem with volume names.

### Expected behavior

Valid Helm-Chart with underscores converted to dashes in K8s resource names.

### Faulty behavior

- Syntax-Errors in chart templates (e.g. volume claims)
- Helm-Chart cannot be applied, because of not k8s compatible names

### Note

- As long as this causes errors a mention in readme would help
- Converting underscores to dashes in docker-compose file also results in a broken chart

**Comment by metal3d** [comment]
Hi, yes right 👍🏻 

I fixed this in https://github.com/metal3d/katenary/commit/d72f371c59857f1ccaa1c1c9e2a246642043d83f

**Comment by metal3d** [comment]
Yep, right, the main problem is that each resource has got its own rule. I missed this one (volume name).

I will fix it tomorrow
