### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by evisanzay** [metal3d/katenary#80]
after a fresh install I tried to convert your example with:

katenary convert -c docker-compose.yml -o ./charts

"Failed to create projectservices.webapp Additional property database is not allowed"

nothing is created

Am I doing something wrong?

**Comment by metal3d** [comment]
It seems that you badly set a "database" attribute in the compose file. Go-Compose yields the errors if the compose file isn't well-formed.

Please, reopen with an example if I'm wrong
